option(BUILD_PLATFORM "Build platform x86\\x64" "x86")

if(BUILD_PLATFORM STREQUAL "x86")
    STRING(APPEND CMAKE_CXX_FLAGS " -m32")
else(BUILD_PLATFORM STREQUAL "x86")
    string(APPEND CMAKE_CXX_FLAGS " -m64")
endif(BUILD_PLATFORM STREQUAL "x86")

string(APPEND CMAKE_CXX_FLAGS " -std=c++11")
